### ISSUE TITLE
Fix app.get('/'

### ISSUE THREAD

**Issue by carlijnbruin** [GuusDijkhuis/dating-app#21]
Hi Femke!

Zou je het pad van app.get('/', die je hebt gebruikt voor het renderen van 'home' willen aanpassen? (in index.js)

Dit i.v.m. dat we er nu twee hebben met hetzelfde pad en het denk ik het beste werkt als de eerste pagina, waar de gebruiker op komt, op deze komt, snap je?

**Comment by Femke-ooster** [comment]
Heb hem aangepast, nu ga je met / naar het registreren en met /home naar de homepagina van match (dashboard)

**Comment by Femke-ooster** [comment]
Aangepaste code kan je hier zien; https://github.com/GuusDijkhuis/dating-app/commit/00238d0f6e2c454fe8e6e4d68e36dd3995f69150
